/**
 * Error Code Enum
 * 
 * Centralized error codes for consistent error handling
 * Backend sends codes, frontend translates to user language
 */

export enum ErrorCode {
  // Authentication Errors (1xxx)
  INVALID_CREDENTIALS = "AUTH_1001",
  UNAUTHORIZED = "AUTH_1002",
  TOKEN_EXPIRED = "AUTH_1003",
  INVALID_TOKEN = "AUTH_1004",
  PHONE_REQUIRED = "AUTH_1005",
  
  // Payment Errors (2xxx)
  PAYMENT_NOT_FOUND = "PAYMENT_2001",
  PAYMENT_ALREADY_CONFIRMED = "PAYMENT_2002",
  PAYMENT_ALREADY_REJECTED = "PAYMENT_2003",
  PAYMENT_EXPIRED = "PAYMENT_2004",
  INVALID_PAYMENT_AMOUNT = "PAYMENT_2005",
  INSUFFICIENT_BALANCE = "PAYMENT_2006",
  PAYMENT_NOT_PENDING = "PAYMENT_2007",
  
  // Contract Errors (3xxx)
  CONTRACT_NOT_FOUND = "CONTRACT_3001",
  CONTRACT_ALREADY_COMPLETED = "CONTRACT_3002",
  CONTRACT_CANCELLED = "CONTRACT_3003",
  INVALID_CONTRACT_DATA = "CONTRACT_3004",
  CONTRACT_HAS_PENDING_PAYMENTS = "CONTRACT_3005",
  
  // Customer Errors (4xxx)
  CUSTOMER_NOT_FOUND = "CUSTOMER_4001",
  CUSTOMER_HAS_ACTIVE_CONTRACTS = "CUSTOMER_4002",
  DUPLICATE_CUSTOMER = "CUSTOMER_4003",
  INVALID_CUSTOMER_DATA = "CUSTOMER_4004",
  
  // Employee Errors (5xxx)
  EMPLOYEE_NOT_FOUND = "EMPLOYEE_5001",
  INSUFFICIENT_PERMISSIONS = "EMPLOYEE_5002",
  EMPLOYEE_INACTIVE = "EMPLOYEE_5003",
  INVALID_EMPLOYEE_DATA = "EMPLOYEE_5004",
  
  // Cash/Balance Errors (6xxx)
  INSUFFICIENT_CASH = "CASH_6001",
  INVALID_CURRENCY = "CASH_6002",
  CASH_REQUEST_NOT_FOUND = "CASH_6003",
  CASH_ALREADY_PROCESSED = "CASH_6004",
  
  // Debtor Errors (7xxx)
  DEBTOR_NOT_FOUND = "DEBTOR_7001",
  DEBTOR_ALREADY_PAID = "DEBTOR_7002",
  
  // General Errors (9xxx)
  INTERNAL_SERVER_ERROR = "ERROR_9001",
  VALIDATION_ERROR = "ERROR_9002",
  NOT_FOUND = "ERROR_9003",
  BAD_REQUEST = "ERROR_9004",
  DATABASE_ERROR = "ERROR_9005",
  FILE_UPLOAD_ERROR = "ERROR_9006",
}

export default ErrorCode;
